Document: webkitkde
Title: Debian webkitkde Manual
Author: <insert document author here>
Abstract: This manual describes what webkitkde is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/webkitkde/webkitkde.sgml.gz

Format: postscript
Files: /usr/share/doc/webkitkde/webkitkde.ps.gz

Format: text
Files: /usr/share/doc/webkitkde/webkitkde.text.gz

Format: HTML
Index: /usr/share/doc/webkitkde/html/index.html
Files: /usr/share/doc/webkitkde/html/*.html


